USE [master]
GO

/****** Object:  Database [FlightManager]    Script Date: 6.2.2022 г. 14:52:07 ******/
CREATE DATABASE [FlightManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FlightManager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FlightManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FlightManager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FlightManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FlightManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FlightManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FlightManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FlightManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FlightManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FlightManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [FlightManager] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [FlightManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FlightManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FlightManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FlightManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FlightManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FlightManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FlightManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FlightManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FlightManager] SET  ENABLE_BROKER 
GO

ALTER DATABASE [FlightManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FlightManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FlightManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FlightManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FlightManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FlightManager] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FlightManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FlightManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [FlightManager] SET  MULTI_USER 
GO

ALTER DATABASE [FlightManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FlightManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FlightManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FlightManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FlightManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FlightManager] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [FlightManager] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FlightManager] SET  READ_WRITE 
GO

